system:
  site_group:
    content_create_view:
      full:
        ezplatform_admin_ui:
          template: '@ezdesign/content/content_edit/content_edit.html.twig'
          match: true
          params:
            viewbaseLayout: '@ezdesign/pagelayout.html.twig'